languageCode = 'en-us'
title = 'TLA+ Foundation'
pygmentsUseClassic = true
PygmentsCodeFences = true
enableRobotsTXT = true
noChmod = true
staticDir = ['static']

[Params]
    disableInlineCopyToClipBoard = false
    disableAssetsBusting = true
    disableLandingPageButton = false
    disableNextPrev = true
    disableSearch = true
    [Params.Author]
        Name = "TLA+ Foundation"
    [Params.ThemeVariant]
        identifier = 'tlaplus'

[markup]
[markup.goldmark.renderer]
    unsafe = true

[module]
[[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'